QOL-8368 add compatibility with CKAN 2.9
qld-gov-au/ckanext-ytp-comments pull request #67
Opened 2022-01-06 00:37 UTC by ThrawnCA

2022-01-06 00:51 UTC, duttonw commented on ckanext/ytp/comments/controllers/__init__.py
> +
might be nice to add comment.

/* Common module functions below */

2022-01-06 01:00 UTC, duttonw commented on .docker/Dockerfile.ckan
> +        pip install -r "${VENV_DIR}/src/ckan/requirements-py2.txt") || \
should we be loading py2, how do we test for python3 and python2 independently?

2022-01-06 02:58 UTC, ThrawnCA commented on ckanext/ytp/comments/templates/package/comment_list.html
> +    &lt;form id="{{ prefix + values.id }}" class="form comment-{{ action }} {% if hidden %}hidden{% endif %}" action="/{{ content_type }}/{{ pkg_id }}/comments/{% if values.id %}{{ values.id }}/{% en
Ah, that's from debugging. I can remove it.

2022-01-06 03:13 UTC, ThrawnCA commented on ckanext/ytp/comments/plugin/flask_plugin.py
> +        return blueprints.get_blueprints()
The idea came from Zharktas' work on `ckanext-report`

2022-01-06 03:25 UTC, duttonw approved these changes

2022-01-06 05:56 UTC, duttonw approved these changes

2022-01-06 23:30 UTC, duttonw requested changes
is getting there, marking as request changes so i should get a delta between now and final

2022-01-07 01:06 UTC, ThrawnCA commented
@duttonw Build is passing now :)

2022-01-07 01:13 UTC, duttonw approved these changes

2022-01-07 04:06 UTC, merged